# Naive Bayes Classifier

In [1]:
import pandas as pd
import numpy as np

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report, confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [3]:
data_dict = load_iris()

In [4]:
df = pd.DataFrame(data = data_dict.data, columns = data_dict.feature_names)

In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df["species"] = data_dict.target

In [7]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  species
0                  5.1               3.5                1.4               0.2        0
1                  4.9               3.0                1.4               0.2        0
2                  4.7               3.2                1.3               0.2        0
3                  4.6               3.1                1.5               0.2        0
4                  5.0               3.6                1.4               0.2        0
..                 ...               ...                ...               ...      ...
145                6.7               3.0                5.2               2.3        2
146                6.3               2.5                5.0               1.9        2
147                6.5               3.0                5.2               2.0        2
148                6.2               3.4                5.4               2.3        2
149                5.9               3.0                5.1               1.8        2

[150 rows x 5 columns]

In [8]:
data_dict.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
x = df.drop("species", axis = 1)

In [10]:
y = df["species"]

In [16]:
df.to_csv('my_dataset.csv', index=False) 

### Train test Split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

### Model Training

In [12]:
gnb_model = GaussianNB()

In [13]:
gnb_model.fit(x_train,y_train)

GaussianNB()

### Model Evaluation

In [14]:
y_pred = gnb_model.predict(x_test)

In [15]:
conf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print()
print("Classification Report:")
print(classification_report(y_test,y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0 13  0]
 [ 0  2 13]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.87      1.00      0.93        13
           2       1.00      0.87      0.93        15

    accuracy                           0.95        38
   macro avg       0.96      0.96      0.95        38
weighted avg       0.95      0.95      0.95        38

